import type { SchemaEdge, SchemaField, SchemaNode } from "./types";

function toSafeIdentifier(input: string): string {
  const trimmed = input.trim();
  if (!trimmed) return "Unnamed";
  const cleaned = trimmed.replace(/[^a-zA-Z0-9_$]/g, "_");
  const startsOk = /^[a-zA-Z_$]/.test(cleaned) ? cleaned : `_${cleaned}`;
  return startsOk || "Unnamed";
}

function toPascalCase(input: string): string {
  const cleaned = input
    .trim()
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  return cleaned || "Collection";
}

function zodForField(field: SchemaField): string {
  let base: string;
  switch (field.kind) {
    case "string":
      base = "z.string()";
      break;
    case "number":
      base = "z.number()";
      break;
    case "boolean":
      base = "z.boolean()";
      break;
    case "custom":
      {
        const custom = field.customType?.trim() ?? "";
        // Keep common TS type expressions intact (generics/unions/namespaces, etc.)
        // but avoid emitting obviously-invalid or injectable content.
        const isValidTypeExpr =
          custom.length > 0 && custom.length <= 200 && !/[\r\n;]/.test(custom);

        base = isValidTypeExpr ? `z.custom<${custom}>()` : "z.unknown()";
      }
      break;
    default:
      base = "z.unknown()";
  }

  if (field.array) base = `${base}.array()`;
  if (!field.required) base = `${base}.optional()`;
  return base;
}

export type GeneratedSchemaArtifacts = {
  typescript: string;
};

export function generateSchemaArtifacts(
  nodes: SchemaNode[],
  edges: SchemaEdge[]
): GeneratedSchemaArtifacts {
  const sortedNodes = [...nodes].sort((a, b) => a.name.localeCompare(b.name));
  const sortedEdges = [...edges].sort((a, b) => a.label.localeCompare(b.label));

  const lines: string[] = [];
  lines.push('import { z } from "zod";');
  lines.push('import { createApp } from "zerithdb-sdk";');
  lines.push("");
  lines.push("/**");
  lines.push(" * Generated by the Visual Schema Builder (MVP).");
  lines.push(" * Edit the schemas below or regenerate from the builder UI.");
  lines.push(" */");
  lines.push("");

  const nameById = new Map<string, string>();
  for (const n of sortedNodes) nameById.set(n.id, n.name);

  for (const node of sortedNodes) {
    const typeName = toPascalCase(node.name);
    const schemaName = `${typeName}Schema`;
    const fieldLines = node.fields
      .filter((f) => f.name.trim().length > 0)
      .map((f) => `  ${JSON.stringify(f.name.trim())}: ${zodForField(f)},`);

    lines.push(`export const ${schemaName} = z.object({`);
    if (fieldLines.length === 0) {
      lines.push("});");
    } else {
      lines.push(...fieldLines);
      lines.push("});");
    }
    lines.push(`export type ${typeName} = z.infer<typeof ${schemaName}>;`);
    lines.push("");
  }

  lines.push("export const relations = [");
  for (const e of sortedEdges) {
    const fromName = nameById.get(e.from) ?? e.from;
    const toName = nameById.get(e.to) ?? e.to;
    lines.push(
      `  { from: ${JSON.stringify(fromName)}, to: ${JSON.stringify(toName)}, label: ${JSON.stringify(
        e.label || "rel"
      )} },`
    );
  }
  lines.push("] as const;");
  lines.push("");
  lines.push("export const app = createApp({");
  lines.push('  appId: "my-app",');
  lines.push('  // sync: { signalingUrl: "wss://signal.zerithdb.dev" },');
  lines.push("  // debug: { devtools: true },");
  lines.push("});");
  lines.push("");

  lines.push("export const db = {");
  for (const node of sortedNodes) {
    const typeName = toPascalCase(node.name);
    const collectionName = node.name.trim() || "unnamed";
    const key = toSafeIdentifier(collectionName);
    lines.push(`  ${key}: () => app.db<${typeName}>(${JSON.stringify(collectionName)}),`);
  }
  lines.push("} as const;");
  lines.push("");

  return { typescript: lines.join("\n") };
}
